{% set version = "2.0.0" %}
{% set ixmp_version = "0.2.0" %}
{% set ixmp_conda_version = "0.2.0" %}
{% set sha256 = "ecaf4d7a5023dbb8196baff3f121715236ec99df8ea7789d8f00213607cbb67c" %}

package:
  name: message-ix
  version: {{ version }}

source:
  url: https://github.com/iiasa/message_ix/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - messageix-config=message_ix.cli:config
    - messageix-dl=message_ix.cli:dl

requirements:
  build:
    - python
    - pip
  run:
    - ixmp =={{ ixmp_conda_version }}

test:
  imports:
    - message_ix
  commands:
    - python -c "import ixmp; assert ixmp.__version__ == '{{ ixmp_version }}'"
    - python -c "import message_ix; assert message_ix.__version__ == '{{ version }}'"
    - messageix-config -h
    - messageix-dl -h
    - messageix-dl --repo_path tutorial
    - python -m message_ix.tools.add_year --help

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The integrated assessment and energy systems model MESSAGEix https://MESSAGEix.iiasa.ac.at/'

extra:
  recipe-maintainers:
    - gidden
    - khaeru
