travis:
  secure:
    BINSTAR_TOKEN: TLIzwWNoty8v+VjOkkBKcKTRkGSabKk7VTzFcbI1YAbTwnUomvKk5kIX1UypbDxlClQllaKMeBy9DHsq6HkuIxjILNJKG2t7sxS70owqPMl57tr+5L3nNxcOoiC0i9RyMesP1Y632p9vERH7BA/hPUu6+gI0PBMmIIUCbVV73x5se6++5G1jw78duizeTyvycmXBKgJalsY1TvGB3tOIwtf/UB6VyuZFth49pOixxz2RlcakcPP8UciSGDSxK8P9jl8dpAo8uKey/zdLf8CuifQB9ePWnxSNQZ1Z/MFiG0imcb1OMepwdOZm8qAqM8OITlfjMglyxYCJKogBGqcMz1u+7RKDpAn3EBd/LAdztV5vhmJLCyGpFJ3FYlmhibnfUSCwxGw9zPtFwOnnTIhUq8l4vQjtX+A+f8v8vlXT6DturGZqcxpGjU+w7rzkWcyR5DB9ywb8LVtlIN3vTEwObqZiBWTzg/lEnCXPl5rHb0RxwnP8AfdJNaFsBIA6NJ+EOflXm2jbERYOkHrNhc6FKJKiyTX6WRb2aGA5PfAg0yqzbssLshIH3oFjB8aYnRmCXWi/nVcTANCLvpwgVAGVJzuCWjvcYBvdVtFG6ylymFntB3kdBo7FtEZSt0+cTOomyeE/l/SjGkEBTNVjjhe9/sr4aJMz5/SYB263+gv8fPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
