travis:
  secure:
    BINSTAR_TOKEN: eZixBND7HzxTXEFklendiRH3qWHKQasTojrUHioQQUxoC6LhghUbJRgq+eZxUi2bUUsx8V0P6IdfZbGKlDbR2f8aDVxdHaJv6o4weZtjE89UZTaGbeZ2T5ZRvvxsoftsHeSy6bp2UhyfGwwP3lBQw5fJNqfcwzWHZtyNRW1IfQQ3G8oBA4T8yS82y8M8i0hLsKs5lebnoSxnUzZbSvwpfV+nZVLwseQ0UzJvBvfvQf0ML+cnby73peaiL0I3kQG8CupHbB9O+lO3CqsK0v1XaXhfhSiqo+rSLodxbDFr4fBLERrsTDw7qojc/5kD9ucEGzhjtXD94mMPBnKPAh6iFT7F/CFZrhTppsWpuEgcehHHe3BM7ks9UE10RR9/06ZYR3AbgJePY+FSh6xwOf84QzmB14OWxMflbb4kvjzU4ReGAYY/VaT1HB4QjhHUo6875MmhhdBlBMh7CUipkYuLJCYNepeHqukaI22g7OInhuEJOtxtuvpgiy5+rgokWC6mhGgmC1TAK1VRm1RKxXNkoqYOXyU8SfqeRJiwCgq1dGHAWY+eeVeQmJ29aoJh5YfP9MaaoSdn8ET54Zqi+cXFIJx6j/XSMHFGjh/nl1KHUgoalOk2ZF1+wxyMcLKcM5v8Zc2bPfQf/kVMHdspwnWRIM5ovlJJTQCyai8cDgZ1rKw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
